name: git-delta-snap
base: core20
adopt-info: delta
summary: A syntax-highlighting pager for git, diff, and grep output
description: |
  Code evolves, and we all spend time studying diffs. Delta aims to make this
  both efficient and enjoyable: it allows you to make extensive changes to the
  layout and styling of diffs, as well as allowing you to stay arbitrarily
  close to the default git/diff output.

  **Configuration**

  Configure your git repository with

    git config core.pager git-delta-snap.delta
    git config interactive.diffFilter "git-delta-snap.delta --color-only"
    git config delta.navigate true
    git config delta.light false
    git config merge.conflictstyle diff3
    git config diff.colorMoved default

website: https://dandavison.github.io/delta/introduction.html
license: MIT

grade: stable
confinement: strict

apps:
  delta:
    command: bin/delta

parts:
  delta:
    plugin: rust
    source: https://github.com/dandavison/delta.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
